purple-technology/phoenix-components

- src/TextArea/TextArea.stories.js
- src/TextArea/TextAreaStyles.tsx
- src/TextArea/index.tsx
I've added textarea component.  
Please review and adjust styling if needed
> Add textarea component

- README.md
- package-lock.json
- package.json
- src/FileUpload/FileUpload.stories.js
- src/FileUpload/FileUploadStyle.tsx
- src/FileUpload/index.tsx
- src/index.tsx
> Fileupload component

- src/Input/Input.stories.js
- src/Input/InputStyles.tsx
- src/Input/index.tsx
- src/SelectBox/SelectStyles.tsx
- src/SelectPicker/SelectPicker.stories.js
- src/SelectPicker/SelectPickerStyles.tsx
- src/SelectPicker/index.tsx
SelectPicker: Fix descriptions on mobile
TextInput: Add helper texts
> Improvements

- src/DateInput/index.tsx
- src/Input/index.tsx
- src/SelectBox/SelectStyles.tsx
- src/SelectBox/index.tsx
- Fix onBlur / onFocus events (fix Formik integration)
- Possibility to display native select on phones instead of react-select
- Add autocomplete params to birthdate input
> Improvements fixes

- .prettierrc.json
- src/Checkbox/Checkbox.stories.js
- src/Checkbox/CheckboxStyles.tsx
- src/Checkbox/index.tsx
- src/DateInput/index.tsx
- src/FileUpload/FileUpload.stories.js
- src/PhoneInput/index.tsx
- src/SelectBox/SelectBox.stories.js
- src/SelectBox/index.tsx
- src/SelectPicker/index.tsx
- src/TextArea/TextArea.stories.js
- src/TextArea/TextAreaStyles.tsx
- src/TextArea/index.tsx
- Prettier all things
- Use better browser check
> Refactoring

- src/DateInput/index.tsx
No breaking changes
https://purpletechnology.atlassian.net/browse/WT-929
> DateInput: Fix init value and rewrite logic

- src/Input/InputStyles.tsx
Make helper text positioned absolutely so we have more control over spacing in other apps.
> Better input helper text

- src/Input/InputStyles.tsx
- src/SelectBox/SelectStyles.tsx
> Fix positioning of errors / helpers

- src/SelectBox/SelectStyles.tsx
Trying to resolve https://github.com/purple-technology/phoenix-components/issues/5
> lowers vertical text alignment in select box

- src/Button/Button.stories.js
- src/Button/ButtonStyles.tsx
- src/Button/index.tsx
- src/index.tsx
Resolves https://github.com/purple-technology/phoenix-components/issues/29
> adds button components

- package-lock.json
- package.json
- src/SelectBox/SelectStyles.tsx
- src/SelectBox/index.tsx
Resolves https://github.com/purple-technology/phoenix-components/issues/17
> Implementation of react-window for virtual loading in SelectBox to

- src/Button/Button.stories.js
- src/Button/ButtonStyles.tsx
- src/Button/index.tsx
- src/DateInput/index.tsx
- src/Input/Input.stories.js
- src/Input/InputStyles.tsx
- src/Input/index.tsx
- src/SelectBox/SelectBox.stories.js
- src/SelectBox/index.tsx
- src/SelectPicker/SelectPicker.stories.js
- src/SelectPicker/SelectPickerStyles.tsx
- src/SelectPicker/index.tsx
- src/TextArea/TextArea.stories.js
- src/TextArea/index.tsx
resolves https://github.com/purple-technology/phoenix-components/issues/37
> Adds defaultProps, additional knobs, and more prop descriptions to

- rollup.config.js
resolves https://github.com/purple-technology/phoenix-components/issues/44
> fixes warnings from rollup

- src/Input/InputStyles.tsx
- src/Input/index.tsx
- src/SelectBox/SelectStyles.tsx
- src/SelectBox/index.tsx
resolves https://github.com/purple-technology/phoenix-components/issues/48
> adds optional description prop to SelectBox

- src/SelectPicker/SelectPickerStyles.tsx
- src/SelectPicker/index.tsx
resolves https://github.com/purple-technology/phoenix-components/issues/50
> adds optional prop for determining SelectPicker color

- src/Input/Input.stories.js
- src/Input/InputStyles.tsx
- src/Input/index.tsx
- src/SelectBox/SelectBox.stories.js
- src/SelectBox/SelectStyles.tsx
- src/SelectBox/index.tsx
resolves https://github.com/purple-technology/phoenix-components/issues/52
> adds optional prop for determining if error position is absolute

- src/DateInput/DateInput.stories.js
- src/DateInput/index.tsx
Work in progress
related to https://github.com/purple-technology/phoenix-components/issues/69
> adds success property to DateInput

- src/Input/index.tsx
Resolves https://github.com/purple-technology/phoenix-components/issues/77
> fixes warning about inputMode in Input component

- src/Input/Input.stories.js
- src/Input/InputStyles.tsx
- src/Input/index.tsx
This was a bad idea and made an already complex component even more complex. I think we should just remove it
> removes descriptionPlacement prop from Input

- src/Alert/Alert.stories.js
- src/Alert/AlertStyles.tsx
- src/Alert/index.tsx
- src/DemoForm/index.tsx
Also includes a small refactor to consolidate `getTextColor` and `getTitleColor` into a single method, since they're returning the same thing anyway
> adds primary alert

- .gitignore
- .vscode/settings.json
- src/Alert/AlertStyles.tsx
- src/Alert/index.tsx
- src/Button/index.tsx
- src/CheckBox/CheckboxStyles.tsx
- src/CheckBox/index.tsx
- src/DateInput/helpers/validate.tsx
- src/DateInput/index.tsx
- src/FileUpload/FileUploadStyle.tsx
- src/FileUpload/index.tsx
- src/Input/InputStyles.tsx
- src/Input/index.tsx
- src/SelectBox/SelectBox.stories.js
- src/SelectBox/SelectStyles.tsx
- src/SelectBox/index.tsx
- src/SelectPicker/SelectPickerStyles.tsx
- src/SelectPicker/index.tsx
- src/TextArea/TextAreaStyles.tsx
- src/TextArea/index.tsx
Resolves https://github.com/purple-technology/phoenix-components/issues/109
> class names and more prop typing

- src/FileUpload/index.tsx
Resolves https://github.com/purple-technology/phoenix-components/issues/112
> callback for pushing files up to the implementing component

- src/FileUpload/index.tsx
Add new param to validate files. If it's not valid, an error message is shown
> Add file validation function

- CHANGELOG.md
- package-lock.json
- package.json
- src/components/SelectPicker/SelectPicker.stories.tsx
- src/components/SelectPicker/index.tsx
fix that prevents render looping and fix for checkbox styling in multiselect mode
> fix: selectpicker component - loop fix and checkbox styling fix

- package.json
Fix #167 didn't help. This one should do the job. Tested ✅
> chore: fix storybook deployment and CircleCI

- CHANGELOG.md
- package-lock.json
- package.json
- rollup.config.js
- src/components/FileUpload/FileUploadStyle.tsx
- src/components/FileUpload/components/FilePreview.tsx
- src/components/FileUpload/index.tsx
- src/theme.tsx
- Render dynamic number of columns based on the actual number of files.
- Previews are all consistently sized (square-shaped).
- `@types/react-pdf` package updated
> Improve FileUpload component previews

- src/components/Link/index.tsx
`ref` prop must have been introduced
> Allow Link component to be used in Dropdown

- CHANGELOG.md
- package-lock.json
- package.json
- src/components/LinkButton/index.tsx
Fixes issue: https://github.com/purple-technology/phoenix-components/issues/181
> forwardRef added to the LinkButton component

- src/components/Notice/NoticeButton.tsx
- src/components/Notice/NoticeStyles.tsx
- src/components/Notice/index.tsx
https://purpletechnology.atlassian.net/jira/software/c/projects/TUX/boards/51?modal=detail&selectedIssue=PUST-193
> feat(Notice): responsiveness improvements

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
- src/components/ClosableButton/ClosableButtonStyles.tsx
- src/components/Heading/HeadingStyles.tsx
- src/components/Link/LinkStyles.tsx
- src/components/Notice/NoticeStyles.tsx
- src/components/Notice/index.tsx
- src/components/SelectNative/index.tsx
- src/components/SelectPicker/SelectPickerStyles.tsx
- src/components/Spacer/SpacerStoriesStyles.tsx
- src/components/Spinner/index.tsx
- src/components/Tabs/TabStyles.tsx
- src/components/TextArea/index.tsx
- src/components/TextInput/index.tsx
- src/components/common/Button/ButtonStyles.tsx
- src/components/common/FormControl/FormControlStyles.tsx
- src/components/common/FormControl/index.tsx
- src/components/common/Select/index.tsx
- src/components/common/Text/TextStyles.tsx
- src/theme.tsx
Several fixes and improvements that I came across while implementing new Login and Register screens in MyAxiory.
- selected tab in Tab component has by default primary color to match the underline
- breakpoint fixes for Notice component and its different variants (basic, with button, with close button, with both button and close button)
- fixed margin props in Spinner component
- added minimal style for FormControl components
- all fixed font weight definitions moved to the theme file
- button properties used from the theme file (previously, some were defined, such as `fontSize`, but were not used)
> Improvements & fixes

- CHANGELOG.md
- package-lock.json
- package.json
- src/components/NumberInput/NumberInput.stories.tsx
- src/components/NumberInput/index.tsx
- src/components/NumberInput/utils.ts
Component only allows a valid number to be entered. Number of decimals can be specified. It is based on TextInput and when an invalid value is entered, it emits an `onChange` event with a `null` value.
> Add NumberInput component

- CHANGELOG.md
- package-lock.json
- package.json
- src/components/Box/index.tsx
- src/components/Tabs/Tab.tsx
Required for [AXSE-267](https://purpletechnology.atlassian.net/browse/AXSE-267)
> Add testId prop to Box and Tab 

- CHANGELOG.md
- package-lock.json
- package.json
- src/components/DateInput/index.tsx
- src/components/DateInput/validate.tsx
- src/components/NumberInput/index.tsx
Optimisation due to https://purpletechnology.atlassian.net/browse/AXI-1709
> feat(DateInput): use number input component

- CHANGELOG.md
- package-lock.json
- package.json
- src/components/DateInput/index.tsx
https://purpletechnology.atlassian.net/browse/PUST-258
> feat(DateInput): new props

- CHANGELOG.md
- package-lock.json
- package.json
- src/components/Tabs/ActiveTabIndicator.tsx
- src/components/Tabs/ActiveTabIndicatorStyles.tsx
- src/components/Tabs/Tab.tsx
- src/components/Tabs/TabList.tsx
- src/components/Tabs/TabStyles.tsx
- src/components/Tabs/Tabs.stories.tsx
- src/components/Tabs/types.tsx
- src/theme.tsx
Added new prop `size`. I added `small`, `medium` and `large`. And plus hover effect.
> feat(Tabs): size prop

- CHANGELOG.md
- package-lock.json
- package.json
- src/components/Modal/index.tsx
Necessary for cases where Modal is wrapped around Next Link component
> fix(Modal): stop propagation

- .storybook/preview.js
- README.md
- src/docs/DesignTokens.stories.mdx
- src/docs/Spacing.stories.mdx
Feedback for new documentation related to version 5 of Phoenix components.
> Feedback for new documentation

- src/components/Dropdown/DropdownStyles.tsx
- src/components/Heading/index.tsx
- src/components/Modal/ModalStyles.tsx
- src/components/Paragraph/index.tsx
- src/components/Text/index.tsx
- src/components/common/Button/ButtonStyles.tsx
- src/components/common/Select/SelectStyles.tsx
- src/components/common/Text/CommonTextProps.tsx
- src/components/common/Text/stories.tsx
- src/tokens/tokens.json
- src/tokens/tokens.scss
- on several places added design tokens instead of static hex values for colors
- updated tokens
- extra improvement: `size` prop taken from common interface for `Text`, `Heading` and `Paragraph` components
> Dark mode improvements

- src/components/CollapsibleCard/CollapsibleCardStyles.tsx
- src/components/CollapsibleCard/index.tsx
@volfpe What do you think about the prop names?
> feat(CollapsibleCard): extended functionality, new props

- CHANGELOG.md
- package-lock.json
- package.json
- src/components/common/Text/CommonTextProps.tsx
- src/components/common/Text/TextStyles.tsx
- src/tokens/tokens.json
- src/tokens/tokens.scss
Because of Purple Zone I had to add support for semibold text.
> feat: font weight semibold

- .circleci/config.yml
- CHANGELOG.md
- package-lock.json
- package.json
- src/components/Label/index.tsx
We weren't propagating props to styled label component...
> fix(Label): props handling

- CHANGELOG.md
- package-lock.json
- package.json
- src/components/DatePicker/index.tsx
- src/components/DateRangePicker/index.tsx
- src/components/TextInput/index.tsx
I included 2 features/fixes here:
- DatePicker and DateRangePicker - right now it's possible to select days that are marked as disabled -> fixed
- added `forwardRef` to TextInput component (needed for custom input on MyAxiory)
> fix(DatePicker): disabled days

- README.md
- src/components/Dropdown/index.tsx
- building tokens with style-dictionary (LAB-41) - @theskupi Please take a look if the changes make sense to you, it's understandable and nothing's missing. Thanks.
- Dropdown: add comment that props are taken from tippy.js (LAB-43)
> Improve docs

- CHANGELOG.md
- package.json
- src/components/DateInput/index.tsx
- src/components/SelectPicker/SelectPickerStyles.tsx
- src/components/Text/TextStyles.tsx
- src/components/common/Select/SelectStyles.tsx
- src/globalStyles.tsx
- component `DateInput` now uses `SelectOption` type for `months` prop instead of custom `Month` (which was unnecessary)
- fixes in tokens for dark mode
- LAB-52 (line height fix)
> LAB-52 + misc fixes

- CHANGELOG.md
- package.json
- src/docs/Colors/index.stories.mdx
- src/docs/DesignTokens.stories.mdx
- src/docs/Spacing.stories.mdx
> LAB-42: Fix broken links in Foundation section

- CHANGELOG.md
- package.json
- pnpm-lock.yaml
- src/components/Button/index.tsx
- src/components/ClosableButton/index.tsx
- src/components/Icon/index.tsx
- src/components/Link/index.tsx
- src/components/LinkButton/index.tsx
- src/components/PasswordInput/PasswordInput.tsx
- src/components/TextInput/index.tsx
- src/components/common/FormControl/index.tsx
- style-dictionary.d.ts
- tsconfig.json
Changing syntax of passing refs from forwardRef to the pass as prop which is new in React 19
> Updating refs to props instead forwardRef
