purple-technology/phoenix-components

src/SelectBox/index.tsx

- Remove use state and use native react-select state
- Fix issue when selectbox didn’t open on tap (mobile devices)

Fix selectbox on mobile

---

src/SelectPicker/index.tsx

Since `onChange` is already being invoked in `onPickerClick` and `useEffect`, I assume this means it'll be called again. Not sure if this is negligible or not, but it fixes the warning

sets onChange in SelectPicker to fix Failed prop type warning

---

src/Checkbox/Checkbox.stories.js
src/Checkbox/index.tsx

Resolves https://github.com/purple-technology/phoenix-components/issues/30
the `onChange` event would not fire in the storybook. I compared it to `SelectPicker` and made it work the same way by handing an `onClick` event to the styled `div` that wraps the `input` element

enables toggling of checkbox in storybook

---

src/SelectBox/SelectStyles.tsx

My previous PR which improved the vertical alignment still had a few issues. I noticed the placeholder text was off-center; this looks like it fixes it

re-centers placeholder text in selectbox when no selection is made

---

src/Input/InputStyles.tsx

when previewing the component with storybook, the `;` was automatically added for us, but it's not getting automatically added for some of the downstream projects

adds missing semi-colon to Input's Error component styling

---

package-lock.json
package.json
src/CheckBox/Checkbox.stories.js

In all the other stories, we're using `@sambego/storybook-state`. To be more consistent, I refactored `Checkbox` to use this as well and removed `storybook-addon-state` as a dependency. This way, we're only using one package for this one purpose

removes storybook-addon-state

---

package-lock.json
package.json
src/Button/Button.stories.js
src/CheckBox/Checkbox.stories.js
src/DateInput/DateInput.stories.js
src/DemoForm/DemoForm.stories.js
src/FileUpload/FileUpload.stories.js
src/Input/Input.stories.js
src/SelectBox/SelectBox.stories.js
src/SelectPicker/SelectPicker.stories.js
src/TextArea/TextArea.stories.js

Solves the deprecation warning about `componentWillReceiveProps` that was coming from both `react-select` and `storybook-react`.
Also changes section dividers from `|` to `/` as recommended for the storybook 6.0 release

upgrades dependencies to resolve deprecation warnings

---

src/Input/index.tsx
src/helpers.tsx

the error is inconsequential, but it's certainly distracting for development, and gets carried into code which implements the component. While I don't like writing code just to get around an error, I think having a dedicated helper function that can be re-used is a decent way to do it
Resolves https://github.com/purple-technology/phoenix-components/issues/79

fixes warning about non bool prop in Input

---

src/SelectBox/SelectStyles.tsx

We have the font size hardcoded for the select input, and it's hard to override since the component is nested so deeply. I've preserved the same ratio and the text still shrinks by 20% when the label is up

replaces Select label's hardcoded fontsize

---

src/FileUpload/FileUploadStyle.tsx
src/FileUpload/components/FilePreview.tsx

When the FileUpload is squashed, since we have auto horizontal margins, the images still have spacing but the PDFs don't in FileUpload. I set the PDF preview component to use `width: 90%` so they'd have the exact spacing as the images, but to accomplish this I had to set a max width on the parent component. This prevents the PDFs from eating up the entire page. It could possibly affect images as well

makes PDF width 90% of container like image files in FileUpload

---

package.json

BREAKING CHANGE: main field in package.json no longer points to dist/index.js but to dist/bundle.umd.js
dist/index.js does not exist when the package has been published. This is fine for webpack/nextjs because they look for the module field in package.json. Which has been set correctly.
But jest resolves a package using the main field which in our case was point to a file which didn't exist, causing unit tests to fail.

fix: changed main field in package.json

---

package.json

Turns out if you set main in package.json to something other than index.js, you also need to set the types property on the package.json to point to the type definitions. Again nextjs works without this but jest does need the types property in order to pick up the type definitions
https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

fix: add type definitions to package.json as main is no longer index.js

---

package.json

It seems that the storybook deployer always force-pushes content of `storybook-static`, so before deployment we need to copy there also `.circleci` folder.

ci: copy circleci files to storybook deployment

---

CHANGELOG.md
package-lock.json
package.json
src/components/Box/Box.stories.mdx
src/components/Box/BoxStyles.tsx
src/components/Flex/Flex.stories.mdx
src/components/Grid/Grid.stories.mdx

- removed `backgroundColor` (not exported by the package) and `opacity` and replaced by `color` which includes `backgroundColor`, `color` and `opacity` (https://styled-system.com/table#color)
- fixed docs

fix(Box): fix in styling related to styled-system

---

.circleci/config.yml

Add commit linting also to CI.
I have picked the last commit (https://github.com/purple-technology/phoenix-components/commit/ecee82ff287af77f21a3f42b2b80a1d96124b1e3) as a reference point since when all the commits will be checked. Because otherwise it checked the whole history which obviously failed because we didn't use conventional commits from the beginning.
Jira task: https://purpletechnology.atlassian.net/browse/PUST-74

ci: add commit linting

---

CHANGELOG.md
package-lock.json
package.json
src/components/Checkbox/index.tsx
src/components/Modal/Modal.stories.tsx
src/components/Modal/index.tsx
src/components/Radio/index.tsx
src/components/common/CheckboxRadio/CheckboxRadioStyles.tsx
src/components/common/CheckboxRadio/index.tsx
src/components/common/CheckboxRadio/stories.tsx

- Modal component - added prop `closeOnOverlayClick`
- Modal component - `onClose` made optional
- Modal component - removed `preventDefault` from `onOverlayClick` - prevented any clicks inside Modal (for example on Buttons)
- `error` and `warning` props added to Checkbox and Radio components and relevant styling introduced

Modal and checkbox/radio improvements

---

CHANGELOG.md
package-lock.json
package.json
src/components/NumberInput/index.tsx

The other common props from HTMLInputElement are not passed to the inner input, which causes problems with Formik integration (namely that `name`) is not set.

fix(NumberInput): pass other htmlinput props to the input

---

CHANGELOG.md
package-lock.json
package.json
src/components/NumberInput/index.tsx

At the moment, when the component has an internal error (wrong number format), it still displays the success tick, if it has the success prop set to true.

fix(NumberInput): do not display success tick when internal error

---

CHANGELOG.md
package-lock.json
package.json
src/components/common/CheckboxRadio/CheckboxRadioStyles.tsx

We have `box-sizing: border-box;` defined globally in `GlobalStyles` component and this component must be used in the app. However, these global styles are somehow loaded a bit later than the component itself (at least I noticed this in MyAxiory). The result is that Checkbox and Radio components in checked state are rendered incorrectly for a split of second on load - see the screenshot. (Because the default value is `content-box` and in the case of Checkbox and Radio components we're directly using the inherent behaviour of `border-box` - keeping the same size regardless of border width)

fix: box-sizing border-box in checkbox and radio

---

CHANGELOG.md
package-lock.json
package.json
src/components/SelectPicker/index.tsx

The error does not include the usual warning triangle. This fixes it.
Before
After

fix(selectpicker): use standard way to render error

---

CHANGELOG.md
package-lock.json
package.json
src/components/SelectNative/index.tsx

Because of this, there's been a bug in AXIORY for at least 6 months. An empty `<option />` was there before but without the empty value condition so it was adding empty value for all native selects which was not a correct behaviour. So it was removed back then. 
This way, the option is added only when there's a discrepancy between React state (undefined value) and options in select that are all defined. Without an empty option, html select cannot be NOT defined.

fix(SelectNative): empty option for undefined value

---

CHANGELOG.md
package-lock.json
package.json
src/components/Box/BoxStyles.tsx
src/components/Box/CommonBoxProps.tsx
src/components/Box/index.tsx
src/components/Notice/NoticeButton.tsx
src/components/Notice/index.tsx
src/components/Pagination/index.tsx
src/components/SelectPicker/SelectPickerStyles.tsx
src/components/SelectPicker/index.tsx
src/components/Tag/TagStyles.tsx
src/components/Tag/index.tsx
src/components/common/Button/ButtonStyles.tsx
src/components/common/Button/index.tsx
src/components/common/Button/stories.tsx
src/components/common/CheckboxRadio/CheckboxRadioStyles.tsx
src/components/common/CheckboxRadio/index.tsx
src/components/common/CheckboxRadio/stories.tsx
src/theme.tsx
src/types/ColorTheme.tsx

- new `gap` prop in `Box` component
- added margin props to `Tag` component
- added theme colors for warning and info
- removed `ButtonColorTheme` and everywhere is now used only `ColorTheme` type
- in `Notice` component `Button` component is used now instead of a separately styled `button` tag
- many new props for an action button in `Notice` component

Box and Notice components - improvements

---

CHANGELOG.md
package-lock.json
package.json
src/components/Modal/index.tsx

Fixed bug that left Modal rendered but invisible (and you couldn't interact with other elements on the page) in scenario where animation is disabled (`animate === false`)
Plus I made two scripts out of the original one `tokens:build` because I sometimes need to update the tokens locally and in that case I want to only build them, but not pull them from repo.

Modal fix - animation false

---

CHANGELOG.md
package.json
pnpm-lock.yaml

Reverting tabs upgrade due to compability with React v17 which is still used in Axiory. Once the pull request with upgrade is go to, we will create release minor version with this upgrade

chore: reverting tabs to older version for temporary React 17 support
